# Generated by Django 2.0.13 on 2019-08-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simposio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='telefone',
            new_name='cpf',
        ),
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
