# Generated by Django 2.0.13 on 2019-08-29 23:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simposio', '0002_auto_20190822_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovado', models.BooleanField()),
                ('data_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.TextField()),
                ('data_aceite', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_aprovacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Area')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Professor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Status')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='submissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Submissao'),
        ),
        migrations.AddField(
            model_name='autores',
            name='submissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simposio.Submissao'),
        ),
    ]
